version = 0.1

[default.deploy.parameters]
stack_name = "raven-lite"
resolve_s3 = true
s3_prefix = "raven-lite"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BedrockModelId=\"amazon.nova-micro-v1:0\""
disable_rollback = false
image_repositories = []

[default.global.parameters]
region = "us-east-1"
